// Generated by tools/airbases.py; terrain-conforming authored runway surfaces.
const int airbaseRunwayCount=6;
const vec4 airbaseRunways[6]=vec4[6](
 vec4(2000.0,2000.0,600.0,40.0),
 vec4(2000.0,4000.0,600.0,40.0),
 vec4(2000.0,6000.0,600.0,40.0),
 vec4(6000.0,2000.0,600.0,40.0),
 vec4(6000.0,4000.0,600.0,40.0),
 vec4(6000.0,6000.0,600.0,40.0));
bool airbaseSurface(vec2 p,out vec3 albedo){
 for(int i=0;i<airbaseRunwayCount;++i){
  vec4 strip=airbaseRunways[i];vec2 q=p-strip.xy;
  if(abs(q.x)>strip.z||abs(q.y)>strip.w)continue;
  float grain=fract(sin(dot(floor(p*2.),vec2(12.9898,78.233)))*43758.5453);
  albedo=vec3(.145,.16,.17)+grain*.025;
  bool edge=abs(q.y)>strip.w-1.5;
  bool centre=abs(q.y)<1.2&&mod(q.x+strip.z,80.)<40.;
  bool threshold=abs(q.x)>strip.z-45.&&abs(q.y)<strip.w-6.&&mod(q.y+strip.w,8.)<4.;
  if(edge||centre||threshold)albedo=vec3(.78,.79,.76);
  return true;
 }
 albedo=vec3(0);return false;
}
