// Generated by tools/terrain_surfaces.py from canonical roads; do not edit.
const int terrainRoadCount = 19;
const vec4 terrainRoadSegments[terrainRoadCount] = vec4[terrainRoadCount](
 vec4(1000.0,1300.0,3800.0,1300.0),
 vec4(3800.0,1300.0,3920.0,1050.0),
 vec4(3920.0,1050.0,4080.0,1050.0),
 vec4(4080.0,1050.0,4200.0,1300.0),
 vec4(4200.0,1300.0,7000.0,1300.0),
 vec4(1000.0,3900.0,3800.0,3900.0),
 vec4(3800.0,3900.0,3920.0,3650.0),
 vec4(3920.0,3650.0,4080.0,3650.0),
 vec4(4080.0,3650.0,4200.0,3900.0),
 vec4(4200.0,3900.0,7000.0,3900.0),
 vec4(1000.0,6500.0,3800.0,6500.0),
 vec4(3800.0,6500.0,3920.0,6250.0),
 vec4(3920.0,6250.0,4080.0,6250.0),
 vec4(4080.0,6250.0,4200.0,6500.0),
 vec4(4200.0,6500.0,7000.0,6500.0),
 vec4(1000.0,1300.0,1000.0,3900.0),
 vec4(1000.0,3900.0,1000.0,6500.0),
 vec4(7000.0,1300.0,7000.0,3900.0),
 vec4(7000.0,3900.0,7000.0,6500.0)
);
const float terrainRoadHalfWidths[terrainRoadCount] = float[terrainRoadCount](
 10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0
);
const uint terrainRoadFlags[terrainRoadCount] = uint[terrainRoadCount](
 1u,1u,1u,1u,1u,1u,1u,1u,1u,1u,1u,1u,1u,1u,1u,1u,1u,1u,1u
);
float terrainRoadDistance(vec2 point, int index) {
 vec4 segment=terrainRoadSegments[index];
 vec2 delta=segment.zw-segment.xy;
 float fraction=clamp(dot(point-segment.xy,delta)/dot(delta,delta),0.,1.);
 return length(point-(segment.xy+fraction*delta));
}
bool terrainRoadContains(vec2 point) {
 for(int i=0;i<terrainRoadCount;++i)
  if((terrainRoadFlags[i]&1u)!=0u && terrainRoadDistance(point,i)<=terrainRoadHalfWidths[i]) return true;
 return false;
}
