// Generated by tools/terrain_relief.py; do not edit.
const int terrainReliefCount=1;
const vec4 terrainReliefX=vec4(5400.0,5480.0,5620.0,5820.0);
const vec4 terrainReliefZ=vec4(4800.0,5000.0,5400.0,5600.0);
const float terrainReliefHeight=64.0;
const uint terrainReliefFlags=1u;
vec2 terrainReliefFactor(float p,vec4 b) {
 if(p<=b.x || p>=b.w) return vec2(0.);
 if(p==b.y || p==b.z) return vec2(1.,0.);
 if(p<b.y) return vec2((p-b.x)/(b.y-b.x),1./(b.y-b.x));
 if(p>b.z) return vec2((b.w-p)/(b.w-b.z),-1./(b.w-b.z));
 return vec2(1.,0.);
}
vec3 terrainRelief(vec2 p) {
 if(any(isnan(p)) || any(isinf(p)) || any(lessThan(p,vec2(0.))) || any(greaterThan(p,vec2(8000.))) || (terrainReliefFlags&1u)==0u) return vec3(0.);
 vec2 x=terrainReliefFactor(p.x,terrainReliefX),z=terrainReliefFactor(p.y,terrainReliefZ);
 return terrainReliefHeight*vec3(x.x*z.x,x.y*z.x,x.x*z.y);
}
