#!/usr/bin/env python3
"""Development-only shared NASM/GLSL generation for authored recovery runways."""
import argparse
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def outputs():
    data = json.loads((ROOT / 'content/terrain/airbases.json').read_text())
    assert data['version'] == 1 and len(data['runways']) == 6
    records = data['runways']
    for i, row in enumerate(records):
        assert set(row) == {'id', 'side', 'front', 'site', 'x', 'z', 'half_length', 'half_width'}
        assert row['id'] == i and row['side'] == i // 3 and row['front'] == i % 3
        assert row['site'] == (0, 4, 8, 3, 7, 11)[i]
        assert all(math.isfinite(row[k]) for k in ('x', 'z', 'half_length', 'half_width'))
        assert 300 <= row['half_length'] <= 800 and 20 <= row['half_width'] <= 100
        assert 0 < row['x'] - row['half_length'] < row['x'] + row['half_length'] < 8000
        assert 0 < row['z'] - row['half_width'] < row['z'] + row['half_width'] < 8000
        for previous in records[:i]:
            assert abs(row['x'] - previous['x']) > row['half_length'] + previous['half_length'] or \
                   abs(row['z'] - previous['z']) > row['half_width'] + previous['half_width']
    asm = '; Generated by tools/airbases.py; canonical airbase/runway records.\n'
    asm += '%include "schemas/air_bases.inc"\n'
    asm += 'global air_bases\nair_bases:\n'
    for row in records:
        asm += ' dd ' + ','.join(str(row[k]) for k in ('x', 'z', 'half_length', 'half_width')) + '\n'
        asm += ' dd ' + ','.join(str(row[k]) for k in ('site', 'side', 'front')) + ',0\n'
    glsl = '// Generated by tools/airbases.py; terrain-conforming authored runway surfaces.\n'
    glsl += 'const int airbaseRunwayCount=6;\nconst vec4 airbaseRunways[6]=vec4[6](\n'
    glsl += ',\n'.join(' vec4(' + ','.join(str(row[k]) for k in ('x', 'z', 'half_length', 'half_width')) + ')' for row in records) + ');\n'
    glsl += '''bool airbaseSurface(vec2 p,out vec3 albedo){
 for(int i=0;i<airbaseRunwayCount;++i){
  vec4 strip=airbaseRunways[i];vec2 q=p-strip.xy;
  if(abs(q.x)>strip.z||abs(q.y)>strip.w)continue;
  float grain=fract(sin(dot(floor(p*2.),vec2(12.9898,78.233)))*43758.5453);
  albedo=vec3(.145,.16,.17)+grain*.025;
  bool edge=abs(q.y)>strip.w-1.5;
  bool centre=abs(q.y)<1.2&&mod(q.x+strip.z,80.)<40.;
  bool threshold=abs(q.x)>strip.z-45.&&abs(q.y)<strip.w-6.&&mod(q.y+strip.w,8.)<4.;
  if(edge||centre||threshold)albedo=vec3(.78,.79,.76);
  return true;
 }
 albedo=vec3(0);return false;
}
'''
    return {ROOT / 'schemas/air_bases_data.inc': asm, ROOT / 'shaders/airbases.glsl': glsl}

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in outputs().items():
        if args.check:
            assert path.read_text() == content, str(path) + ' stale: run tools/airbases.py'
        elif not path.exists() or path.read_text() != content:
            path.write_text(content)
    print(json.dumps({'airbases': 6, 'checked': args.check}))
