#!/usr/bin/env python3
"""Development-only canonical layout emitter."""
import hashlib,json,pathlib
root=pathlib.Path(__file__).resolve().parents[1]
s=json.loads((root/'schemas/entity.json').read_text())
lines=['; Generated by tools/schema.py; do not edit.',f'%define ENTITY_STRIDE {s["stride"]}',f'%define ENTITY_CAPACITY {s["capacity"]}',f'%define ENTITY_SCHEMA_VERSION {s["version"]}']
used=set()
for name,(offset,kind) in s['fields'].items():
    assert kind in ('f32','u32','i32') and offset%4==0 and offset+4<=s['stride']
    assert offset not in used
    used.add(offset); lines.append(f'%define ENTITY_{name.upper()} {offset}')
lines.append('; fingerprint '+hashlib.sha256(json.dumps(s,sort_keys=True).encode()).hexdigest())
out=root/'schemas/entity.inc'
text='\n'.join(lines)+'\n'
if not out.exists() or out.read_text()!=text: out.write_text(text)
