#!/usr/bin/env python3
"""Generate bounded static NASM/GLSL road data; development-only tool."""
import argparse
import json
import math
import os
from pathlib import Path
import struct
import tempfile

ROOT = Path(__file__).resolve().parents[1]
LIMIT = 19

def f32(value):
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError('road numbers must be finite real numbers')
    try:
        if not math.isfinite(value):
            raise ValueError('road numbers must be finite real numbers')
        result = struct.unpack('<f', struct.pack('<f', value))[0]
    except (OverflowError, struct.error) as exc:
        raise ValueError('road number exceeds float32 range') from exc
    if not math.isfinite(result):
        raise ValueError('road numbers must fit finite float32')
    return result

def validate(document):
    if not isinstance(document, dict) or set(document) != {'version', 'roads'}:
        raise ValueError('document requires exactly version and roads')
    if type(document['version']) is not int or document['version'] != 1:
        raise ValueError('unsupported road schema version')
    roads = document['roads']
    if not isinstance(roads, list) or not 1 <= len(roads) <= LIMIT:
        raise ValueError(f'road count must be 1..{LIMIT}')
    records = []
    for road in roads:
        if not isinstance(road, dict) or set(road) != {'from', 'to', 'half_width', 'flags'}:
            raise ValueError('road requires from, to, half_width and flags')
        point = []
        for field in ('from', 'to'):
            if not isinstance(road[field], list) or len(road[field]) != 2:
                raise ValueError('road endpoints must be two-coordinate arrays')
            for value in road[field]:
                rounded = f32(value)
                if not 0 <= value <= 8000 or not 0 <= rounded <= 8000:
                    raise ValueError('road endpoint outside operation map')
                point.append(rounded)
        if math.hypot(point[2]-point[0],point[3]-point[1]) < .001:
            raise ValueError('road segment float32 length must be at least 0.001m')
        width = f32(road['half_width'])
        if not .001 <= road['half_width'] <= 8000 or not .001 <= width <= 8000:
            raise ValueError('road paved half-width must be 0.001..8000m')
        if type(road['flags']) is not int or road['flags'] != 1:
            raise ValueError('road flags must be 1')
        records.append((*point, width, 1))
    return records

def literal(value):
    # Nine significant decimal digits round-trip every finite float32.
    result = format(value, '.9g')
    return result if '.' in result or 'e' in result else result + '.0'

def render(records):
    nasm = ['; Generated by tools/terrain_surfaces.py from canonical roads; do not edit.',
            '%define TERRAIN_ROAD_COUNT ' + str(len(records)),
            'global terrain_road_count,terrain_road_segments',
            'terrain_road_count: dd TERRAIN_ROAD_COUNT', 'align 16', 'terrain_road_segments:']
    glsl = ['// Generated by tools/terrain_surfaces.py from canonical roads; do not edit.',
            'const int terrainRoadCount = ' + str(len(records)) + ';',
            'const vec4 terrainRoadSegments[terrainRoadCount] = vec4[terrainRoadCount](']
    for index, row in enumerate(records):
        nasm.append(' dd ' + ','.join(literal(v) for v in row[:5]) + ',' + str(row[5]))
        glsl.append(' vec4(' + ','.join(literal(v) for v in row[:4]) + ')' + (',' if index+1<len(records) else ''))
    glsl.extend([');', 'const float terrainRoadHalfWidths[terrainRoadCount] = float[terrainRoadCount](',
                 ' ' + ','.join(literal(row[4]) for row in records), ');',
                 'const uint terrainRoadFlags[terrainRoadCount] = uint[terrainRoadCount](',
                 ' ' + ','.join(str(row[5])+'u' for row in records), ');',
                 'float terrainRoadDistance(vec2 point, int index) {',
                 ' vec4 segment=terrainRoadSegments[index];',
                 ' vec2 delta=segment.zw-segment.xy;',
                 ' float fraction=clamp(dot(point-segment.xy,delta)/dot(delta,delta),0.,1.);',
                 ' return length(point-(segment.xy+fraction*delta));', '}',
                 'bool terrainRoadContains(vec2 point) {',
                 ' for(int i=0;i<terrainRoadCount;++i)',
                 '  if((terrainRoadFlags[i]&1u)!=0u && terrainRoadDistance(point,i)<=terrainRoadHalfWidths[i]) return true;',
                 ' return false;', '}', ''])
    return '\n'.join(nasm)+'\n', '\n'.join(glsl)

def generate(source, nasm_path, glsl_path, check=False):
    records = validate(json.loads(source.read_text()))
    nasm_text,glsl_text = render(records)
    outputs = [(nasm_path, nasm_text), (glsl_path, glsl_text)]
    if len({path.resolve() for path, _ in outputs}) != 2:
        raise ValueError('NASM and GLSL output paths must differ')
    if source.resolve() in {path.resolve() for path, _ in outputs}:
        raise ValueError('outputs must not overwrite canonical source')
    if check:
        if any(not path.exists() or path.read_text() != value for path,value in outputs):
            raise ValueError('generated terrain road outputs are stale')
        return len(records)
    # Validate and render everything before touching either destination. Prepare
    # both temporary files before publication; malformed sources never write.
    pending=[]
    try:
        for path,value in outputs:
            path.parent.mkdir(parents=True, exist_ok=True)
            with tempfile.NamedTemporaryFile(mode='w', dir=path.parent, prefix='.terrain-roads-', delete=False) as file:
                pending.append((Path(file.name),path))
                file.write(value)
                file.flush()
                os.fsync(file.fileno())
        for temporary,destination in pending:
            os.replace(temporary,destination)
    finally:
        for temporary,_ in pending:
            temporary.unlink(missing_ok=True)
    return len(records)

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=ROOT/'content/terrain/roads.json')
    parser.add_argument('--nasm', type=Path, default=ROOT/'schemas/terrain_roads.inc')
    parser.add_argument('--glsl', type=Path, default=ROOT/'shaders/terrain_roads.glsl')
    parser.add_argument('--check', action='store_true')
    args=parser.parse_args()
    try:
        count=generate(args.source,args.nasm,args.glsl,args.check)
    except (ValueError,OSError) as exc:
        parser.exit(2, f'terrain roads: {exc}\n')
    print(json.dumps({'terrain_roads':count,'checked':args.check}))

if __name__=='__main__':
    main()
