#!/usr/bin/env python3
"""Generate bounded grade facets from canonical float32 relief; development only."""
import argparse,json,math,os,re,tempfile
from pathlib import Path
from terrain_relief import validate as relief_validate
ROOT=Path(__file__).resolve().parents[1]
def validate(document):
    field=relief_validate(document)[0]
    x=field[:4];z=field[4:8];h=field[8]
    if not (x[3]<=3200 or x[0]>=4800):
        raise ValueError('grade support must not intersect ridge interior X3200..4800')
    def pieces(b):
        return [(b[0],b[1],1/(b[1]-b[0]),-b[0]/(b[1]-b[0])),
                (b[1],b[2],0.,1.),
                (b[2],b[3],-1/(b[3]-b[2]),b[3]/(b[3]-b[2]))]
    facets=[]
    for xa,xb,kx,mx in pieces(x):
        for za,zb,kz,mz in pieces(z):
            facets.append((xa,za,xb,zb,h*kx*kz,h*kx*mz,h*kz*mx,1))
    assert len(facets)==9 and all(math.isfinite(v) for row in facets for v in row)
    # Global bowl+ridge gradient bound, independent of field coefficients.
    contract=(ROOT/'schemas/terrain_grade.inc').read_text()
    def constant(name):
        match=re.search(r'^%define '+name+r' ([^\s;]+)',contract,re.M)
        if not match:raise ValueError('missing grade contract constant '+name)
        value=float(match[1])
        if not math.isfinite(value):raise ValueError('non-finite grade policy')
        return value
    caps=[constant('GRADE_'+role+'_LIMIT_SQ') for role in ('INF','TANK','ARTY')]
    guard=constant('GRADE_GUARD_SQ')
    bx,bz=constant('GRADE_BASE_X'),constant('GRADE_BASE_Z')
    if bx!=.000002 or bz!=.000001 or guard<0:
        raise ValueError('grade base/guard differs from checked terrain invariant')
    if not (math.hypot(.0225,.004)<.023 and .023**2+guard<min(caps)):
        raise ValueError('grade policies do not safely clear existing shallow base')
    return facets

def literal(value):
    result=format(value,'.17g')
    return result if '.' in result or 'e' in result else result+'.0'

def render(facets):
    return '\n'.join(['; Generated by tools/terrain_grade.py; do not edit.',
        '%define TERRAIN_GRADE_COUNT 9','global terrain_grade_count,terrain_grade_facets',
        'terrain_grade_count: dd TERRAIN_GRADE_COUNT','align 16','terrain_grade_facets:',
        *(' dq '+','.join(literal(v) for v in row[:7])+',1' for row in facets),''])

def generate(source,output,check=False):
    text=render(validate(json.loads(source.read_text())))
    if source.resolve()==output.resolve():raise ValueError('source and output must differ')
    if check:
        if not output.exists() or output.read_text()!=text:raise ValueError('generated grade output stale')
        return 9
    output.parent.mkdir(parents=True,exist_ok=True)
    pending=None
    try:
        with tempfile.NamedTemporaryFile(mode='w',dir=output.parent,prefix='.terrain-grade-',delete=False) as handle:
            pending=Path(handle.name);handle.write(text);handle.flush();os.fsync(handle.fileno())
        os.replace(pending,output)
    finally:
        if pending:pending.unlink(missing_ok=True)
    return 9

def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--source',type=Path,default=ROOT/'content/terrain/relief.json')
    p.add_argument('--nasm',type=Path,default=ROOT/'schemas/terrain_grade_data.inc')
    p.add_argument('--check',action='store_true');a=p.parse_args()
    try:n=generate(a.source,a.nasm,a.check)
    except (ValueError,OSError) as e:p.exit(2,f'terrain grade: {e}\n')
    print(json.dumps({'terrain_grade_facets':n,'checked':a.check}))
if __name__=='__main__':main()
