#!/usr/bin/env python3
"""Generate the bounded static raised-relief component; development only."""
import argparse,json,math,os,struct,tempfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def f32(value):
    if isinstance(value,bool) or not isinstance(value,(int,float)):
        raise ValueError('relief numbers must be finite real numbers')
    try:
        if not math.isfinite(value):raise ValueError('non-finite relief number')
        rounded=struct.unpack('<f',struct.pack('<f',value))[0]
    except (OverflowError,struct.error) as exc:raise ValueError('relief number exceeds float32') from exc
    if not math.isfinite(rounded):raise ValueError('non-finite float32 relief number')
    return rounded

def validate(doc):
    if not isinstance(doc,dict) or set(doc)!={'schema','fields'}:raise ValueError('expected schema and fields only')
    if type(doc['schema']) is not int or doc['schema']!=1:raise ValueError('unsupported relief schema')
    if not isinstance(doc['fields'],list) or len(doc['fields'])!=1:raise ValueError('exactly one relief field required')
    field=doc['fields'][0]
    if not isinstance(field,dict) or set(field)!={'x','z','height','flags'}:raise ValueError('expected x, z, height, flags only')
    record=[]
    for axis in ('x','z'):
        values=field[axis]
        if not isinstance(values,list) or len(values)!=4:raise ValueError('axis requires four breaks')
        rounded=[f32(v) for v in values]
        if any(not 0<=v<=8000 for v in values+rounded):raise ValueError('axis outside map')
        if not (rounded[0]<rounded[1]<=rounded[2]<rounded[3]):raise ValueError('axis breaks not ordered after rounding')
        if rounded[1]-rounded[0]<1 or rounded[3]-rounded[2]<1:raise ValueError('rounded ramp width must be at least one metre')
        record.extend(rounded)
    height=f32(field['height'])
    if not 0<field['height']<=1000 or not 0<height<=1000:raise ValueError('height must be positive and at most 1000')
    if type(field['flags']) is not int or field['flags']!=1:raise ValueError('flags must be integer 1')
    return [(*record,height,1)]

def literal(v):
    s=format(v,'.9g');return s if '.' in s or 'e' in s else s+'.0'

def render(records):
    r=records[0]
    nasm='\n'.join(['; Generated by tools/terrain_relief.py; do not edit.','%define TERRAIN_RELIEF_COUNT 1','global terrain_relief_count,terrain_relief_fields','terrain_relief_count: dd TERRAIN_RELIEF_COUNT','align 16','terrain_relief_fields:',' dd '+','.join(literal(v) for v in r[:9])+',1',''])
    glsl='\n'.join(['// Generated by tools/terrain_relief.py; do not edit.','const int terrainReliefCount=1;','const vec4 terrainReliefX=vec4('+','.join(literal(v) for v in r[:4])+');','const vec4 terrainReliefZ=vec4('+','.join(literal(v) for v in r[4:8])+');','const float terrainReliefHeight='+literal(r[8])+';','const uint terrainReliefFlags=1u;','vec2 terrainReliefFactor(float p,vec4 b) {',' if(p<=b.x || p>=b.w) return vec2(0.);',' if(p==b.y || p==b.z) return vec2(1.,0.);',' if(p<b.y) return vec2((p-b.x)/(b.y-b.x),1./(b.y-b.x));',' if(p>b.z) return vec2((b.w-p)/(b.w-b.z),-1./(b.w-b.z));',' return vec2(1.,0.);','}','vec3 terrainRelief(vec2 p) {',' if(any(isnan(p)) || any(isinf(p)) || any(lessThan(p,vec2(0.))) || any(greaterThan(p,vec2(8000.))) || (terrainReliefFlags&1u)==0u) return vec3(0.);',' vec2 x=terrainReliefFactor(p.x,terrainReliefX),z=terrainReliefFactor(p.y,terrainReliefZ);',' return terrainReliefHeight*vec3(x.x*z.x,x.y*z.x,x.x*z.y);','}',''])
    return nasm,glsl

def generate(source,nasm_path,glsl_path,check=False):
    records=validate(json.loads(source.read_text()));outputs=list(zip((nasm_path,glsl_path),render(records)))
    paths={p.resolve() for p,_ in outputs}
    if len(paths)!=2 or source.resolve() in paths:raise ValueError('source and both outputs must differ')
    if check:
        if any(not p.exists() or p.read_text()!=s for p,s in outputs):raise ValueError('generated relief outputs stale')
        return 1
    pending=[]
    try:
        for p,s in outputs:
            p.parent.mkdir(parents=True,exist_ok=True)
            with tempfile.NamedTemporaryFile(mode='w',dir=p.parent,prefix='.terrain-relief-',delete=False) as f:
                pending.append((Path(f.name),p));f.write(s);f.flush();os.fsync(f.fileno())
        for tmp,p in pending:os.replace(tmp,p)
    finally:
        for tmp,_ in pending:tmp.unlink(missing_ok=True)
    return 1

def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--source',type=Path,default=ROOT/'content/terrain/relief.json');p.add_argument('--nasm',type=Path,default=ROOT/'schemas/terrain_relief_data.inc');p.add_argument('--glsl',type=Path,default=ROOT/'shaders/terrain_relief.glsl');p.add_argument('--check',action='store_true');a=p.parse_args()
    try:n=generate(a.source,a.nasm,a.glsl,a.check)
    except (ValueError,OSError) as e:p.exit(2,f'terrain relief: {e}\n')
    print(json.dumps({'terrain_relief_fields':n,'checked':a.check}))
if __name__=='__main__':main()
